package com.lukas.ramonas.cms.DAO;

import com.lukas.ramonas.cms.Model.User;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
public class MainController {
    // This means to get the bean called user_tableRepository
    // Which is auto-generated by Spring, we will use it to handle the data

    @GetMapping("/tete")
    public String showHome(Model model) {
        return "register";
    }

    @Autowired
    private UserRepository UserRepository;

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return UserRepository.findAll();
    }

}